name: server_catworm

description: mobile ssh client 
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  http: ^0.12.1
  cupertino_icons: ^0.1.3
  majascan: ^0.4.0
  xterm: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
