name: server_catworm

description: mobile ssh client 
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  http: ^0.12.1
  cupertino_icons: ^0.1.3
  xterm: ^2.0.0
  flutter_slidable: ^0.6.0
  get_storage: ^2.0.2
  qr_code_scanner: ^0.4.0
  sliding_up_panel: ^2.0.0+1
  flutter_phoenix: ^1.0.0
  google_fonts: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
